 FROM nginx
# RUN rm /usr/share/nginx/html/index.html
# RUN echo "I am Siddharth" > /usr/share/nginx/html/index.html
# COPY index.html /usr/share/nginx/html/
ADD --chmod=777 https://raw.githubusercontent.com/bradtraversy/50projects50days/refs/heads/master/background-slider/index.html /usr/share/nginx/html/



#WORKDIR /photos
#COPY . .